### ISSUE TITLE
Jupyter CILogon twice

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/fabricauthenticator#4]
If your jupyter container is down, you are asked to login to CILogon twice when you start jupyter.  Can this be reduce to only once?

**Comment by kthare10** [comment]
`Fabricauthenticator` overrides the default implementation for `refresh_user`. `refresh_user` to force a logout/login in order to refresh the tokens and oauth state.

`refresh_user` is invoked in following two scenarios controlled by the respective JH config parameters.
- Scenario 1
User container has reached the maximum age of 24 hours and has been stopped. In this case, re-login is forced. This is controlled by the two parameters `maxAge` and `auth_refresh_age` both set to `86400` seconds
- Scenario 2
Refresh before spawning the container. This is the root cause for dual logins. So even if user just logged in, container's pre_spawn_hook is triggered forcing a re-authentication. This is controlled by `refresh_pre_spawn` set to `True` in the current deployment.

Changing `refresh_pre_spawn` to False disables the two logins. But it also has a side effect that restarting the notebook container cannot be used as a solution to handle scenarios when user's refresh token becomes invalid. In these cases, users would have to download the token from the portal and upload to the JH.
